function Hd = HD
%HD Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 18-Jun-2018 20:44:49

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 682666.66667;  % Sampling Frequency

Fpass = 40666.666667;    % Passband Frequency
Fstop = 42666.666667;    % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.001;           % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
